import { NextResponse } from "next/server";
import { generatePDFReport } from "@/lib/pdfReports";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const result = await generatePDFReport({
      title: body.title || "Accessibility Compliance Report",
      summary: body.summary || "Generated by Accessana Pro AI Engine.",
      sections: body.sections || [],
    });
    return NextResponse.json({ ok: true, file: result.path });
  } catch (e: any) {
    console.error("PDF error:", e);
    return NextResponse.json({ ok: false, error: e.message }, { status: 500 });
  }
}
